/**
 * Payload CMS generated types
 * This file will be auto-generated by Payload CMS
 */

export interface Page {
  id: string;
  title: string;
  slug: string;
  seo?: {
    title?: string;
    description?: string;
    noIndex?: boolean;
  };
  [key: string]: unknown;
}

export interface Article {
  id: string;
  title: string;
  slug: string;
  seo?: {
    title?: string;
    description?: string;
    noIndex?: boolean;
  };
  [key: string]: unknown;
}

export interface Space {
  id: string;
  title: string;
  slug: string;
  seo?: {
    title?: string;
    description?: string;
    noIndex?: boolean;
  };
  [key: string]: unknown;
}
